backend:
  name: github
  repo: pierciromoggio/casavacanza
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pagine"
    files:
      - file: "index.html"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Titolo", name: "title", widget: "string" }
          - { label: "Testo principale", name: "body", widget: "text" }
